apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}-service
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.ports.amqp }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.service.ports.management }}
      targetPort: management
      protocol: TCP
  selector:
    app.kubernetes.io/component: {{ .Values.rabbitmq.name }}
