apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.defaultUser | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.defaultPass | b64enc | quote }}
