apiVersion: v1
kind: PersistentVolume
metadata:
  name: conv-api-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/conv-api-uploads
    type: DirectoryOrCreate
