apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: U0VFRF9VU0VSX05BTUU=
  password: U0VFRF9VU0VSX1BBU1NXT1JE
  erlangCookie: dzhhK1czNnJ3VmFTMFM4alpTc3J0YWRqZTRsT2NZOXU=
  AMQP_EXCHANGE: Y29udmVyc2lvbi1leGNoYW5nZQ==
