apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip
spec:
  type: ClusterIP
  selector:
    component: rabbitmq
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
  - name: management
    port: 15672
    protocol: TCP
  - name: cluster
    port: 25672
    protocol: TCP
