apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.secrets.defaultUser | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.secrets.defaultPass | b64enc | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.secrets.erlangCookie | b64enc | quote }}
